### ISSUE TITLE
What is the difference between these three models?

### ISSUE THREAD

**Issue by wuyifan18** [JetBrains-Research/code2seq#110]
code2seq
typed-code2seq
code2class

**Comment by SpirinEgor** [comment]
Hi!

- Code2seq is a vanilla model that used LSTM to embed paths into vectors and then uses another LSTM to generate output sequence (e.g. method name)
- Code2class uses the same encoding method, but as a decoder, it has MLP to the number of classes. It is useful for classification tasks or when you need to build embedding of the code.
- Typed-code2seq is extended code2seq model. We describe it in paper about [PSIMiner](https://arxiv.org/abs/2103.12778)

**Comment by wuyifan18** [comment]
Thank you!

**Comment by Avra2** [comment]
@SpirinEgor. Thank you very much. Do you have documentation please of Code2class or published paper so that we can read more and cite it?

**Comment by SpirinEgor** [comment]
Currently, we don't have a paper that uses the code2class model. Hope to have one soon :)
To better understand how it works, I may suggest you study the difference between vanilla code2seq and code2vec models. Code2Class indeed uses code2seq encoder (path embedding algorithm) and code2vec decoder (path aggregation and processing output vector).
