### ISSUE TITLE
can i get an information about the java-med dataset parser?

### ISSUE THREAD

**Issue by hehehwang** [JetBrains-Research/code2seq#113]
(from #109) i'm trying make inference with [code2seq-java-med.yaml](https://github.com/JetBrains-Research/code2seq/blob/master/config/code2seq-java-med.yaml)

from the dataset, i found 'java_paths_methods.json', which looks very similar to older version of [astminer](https://github.com/JetBrains-Research/astminer) configuration fille, but i couldn't figure it out more.
can you help me with this?

**Comment by SpirinEgor** [comment]
These datasets were extracted with the `PSIMiner` tool.
Here is [the GitHub link](https://github.com/JetBrains-Research/psiminer).

It's quite the same tool as astminer, but it uses IntelliJ Platform as a language tool.
